"""Metadata introspection for the LavaSR plugin used by cjm-ctl to generate the registration manifest.

Docs: https://cj-mills.github.io/cjm-media-plugin-lavasrmeta.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/meta.ipynb.

# %% auto #0
__all__ = ['get_plugin_metadata']

# %% ../nbs/meta.ipynb #17c78597
import os
import sys
from typing import Any, Dict
from . import __version__

# %% ../nbs/meta.ipynb #d470aa29
def get_plugin_metadata() -> Dict[str, Any]:  # Plugin metadata for manifest generation
    """Return metadata required to register this plugin with the PluginManager."""
    # Fallback base path (current behavior for backward compatibility)
    base_path = os.path.dirname(os.path.dirname(sys.executable))
    
    # Use CJM config if available, else fallback to env-relative paths
    cjm_data_dir = os.environ.get("CJM_DATA_DIR")
    cjm_models_dir = os.environ.get("CJM_MODELS_DIR")
    
    # Plugin data directory
    plugin_name = "cjm-media-plugin-lavasr"
    if cjm_data_dir:
        data_dir = os.path.join(cjm_data_dir, plugin_name)
    else:
        data_dir = os.path.join(base_path, "data")
    
    db_path = os.path.join(data_dir, "lavasr_jobs.db")
    
    # Ensure data directory exists
    os.makedirs(data_dir, exist_ok=True)
    
    # HuggingFace cache: LavaSR uses huggingface_hub.snapshot_download()
    if cjm_models_dir:
        hf_home = os.path.join(cjm_models_dir, "huggingface")
    else:
        hf_home = os.path.join(base_path, ".cache", "huggingface")
    
    return {
        "name": plugin_name,
        "version": __version__,
        "type": "media-processing",
        "category": "media",
        "interface": "cjm_media_plugin_system.processing_interface.MediaProcessingPlugin",
        
        "module": "cjm_media_plugin_lavasr.plugin",
        "class": "LavaSRProcessingPlugin",
        
        # Critical: The absolute path to THIS environment's python
        "python_path": sys.executable,
        
        "db_path": db_path,
        
        "resources": {
            "requires_gpu": False,
            "min_gpu_vram_mb": 512,
            "recommended_gpu_vram_mb": 1024,
            "min_system_ram_mb": 2048
        },
        
        "env_vars": {
            "HF_HOME": hf_home
        }
    }
